apiVersion: gateway.solo.io/v1
kind: VirtualHostOption
metadata:
  name: waf
  namespace: ingress-gw
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw
      namespace: ingress-gw
  options:
    waf:
      configMapRuleSets:
        - configMapRef:
            name: waf-rules
            namespace: ingress-gw
